export const PERMISSIONS = {
  PROJECT_CREATE: "PROJECT_CREATE",
  PROJECT_READ: "PROJECT_READ",
  PROJECT_PLAN_UPDATE: "PROJECT_PLAN_UPDATE",
  TASK_PROGRESS_UPDATE: "TASK_PROGRESS_UPDATE",
  GATE_SUBMIT: "GATE_SUBMIT",
  GATE_APPROVE: "GATE_APPROVE",
  ACCEPTANCE_READ: "ACCEPTANCE_READ",
  ACCEPTANCE_RESULT_UPDATE: "ACCEPTANCE_RESULT_UPDATE",
  ACCEPTANCE_EVIDENCE_MANAGE: "ACCEPTANCE_EVIDENCE_MANAGE",
  ACCEPTANCE_REVIEW: "ACCEPTANCE_REVIEW",
  PORTFOLIO_READ: "PORTFOLIO_READ",
  PROJECT_MEMBER_READ: "PROJECT_MEMBER_READ",
  PROJECT_MEMBER_MANAGE: "PROJECT_MEMBER_MANAGE",
  CONFIGURATION_READ: "CONFIGURATION_READ",
  CONFIGURATION_WRITE: "CONFIGURATION_WRITE",
  JOB_REPLAY: "JOB_REPLAY",
  FILE_UPLOAD: "FILE_UPLOAD",
  FILE_DOWNLOAD: "FILE_DOWNLOAD",
  SENSITIVE_FILE_READ: "SENSITIVE_FILE_READ",
  SENSITIVE_CONTRACT_READ: "SENSITIVE_CONTRACT_READ",
  SENSITIVE_CONFIRMATION_READ: "SENSITIVE_CONFIRMATION_READ",
  AUDIT_READ: "AUDIT_READ"
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_SCOPES = {
  ALL: "ALL",
  DEPARTMENT: "DEPARTMENT",
  PROJECT: "PROJECT",
  SELF: "SELF",
  ASSIGNED: "ASSIGNED"
} as const;

export type PermissionScope = (typeof PERMISSION_SCOPES)[keyof typeof PERMISSION_SCOPES];

export const SYSTEM_ROLES = {
  PROJECT_MANAGER: "PROJECT_MANAGER",
  DEPARTMENT_LEAD: "DEPARTMENT_LEAD",
  ENGINEER: "ENGINEER",
  PROCUREMENT: "PROCUREMENT",
  QUALITY: "QUALITY",
  EXECUTIVE: "EXECUTIVE",
  ADMIN: "ADMIN"
} as const;

export type SystemRoleCode = (typeof SYSTEM_ROLES)[keyof typeof SYSTEM_ROLES];

export const PROJECT_ROLES = {
  PROJECT_MANAGER: "PROJECT_MANAGER",
  DEPARTMENT_LEAD: "DEPARTMENT_LEAD",
  ENGINEER: "ENGINEER",
  PROCUREMENT: "PROCUREMENT",
  QUALITY: "QUALITY",
  VIEWER: "VIEWER"
} as const;

export type ProjectRoleCode = (typeof PROJECT_ROLES)[keyof typeof PROJECT_ROLES];

export const PROJECT_ROLE_VALUES = Object.values(PROJECT_ROLES);
