import { describe, expect, it } from "vitest";

import {
  AUDIT_ACTIONS,
  AUDIT_OBJECT_TYPES,
  PUBLIC_LIBRARY_AUDIT_FIELDS
} from "@/modules/audit/domain/vocabulary";

describe("APM-060 public-library audit vocabulary", () => {
  it("declares append-only public-document and exact-reference audit facts", () => {
    expect(AUDIT_ACTIONS).toMatchObject({
      PUBLIC_LIBRARY_DOCUMENT_CREATED: "PUBLIC_LIBRARY_DOCUMENT_CREATED",
      PUBLIC_LIBRARY_VERSION_DRAFTED: "PUBLIC_LIBRARY_VERSION_DRAFTED",
      PUBLIC_LIBRARY_VERSION_PUBLISHED: "PUBLIC_LIBRARY_VERSION_PUBLISHED",
      PUBLIC_LIBRARY_DOCUMENT_VOIDED: "PUBLIC_LIBRARY_DOCUMENT_VOIDED",
      PROJECT_PUBLIC_LIBRARY_REFERENCE_CREATED: "PROJECT_PUBLIC_LIBRARY_REFERENCE_CREATED",
      PROJECT_PUBLIC_LIBRARY_REFERENCE_RETIRED: "PROJECT_PUBLIC_LIBRARY_REFERENCE_RETIRED"
    });
    expect(AUDIT_OBJECT_TYPES).toMatchObject({
      PUBLIC_LIBRARY_DOCUMENT: "PUBLIC_LIBRARY_DOCUMENT",
      PUBLIC_LIBRARY_DOCUMENT_VERSION: "PUBLIC_LIBRARY_DOCUMENT_VERSION",
      PROJECT_PUBLIC_LIBRARY_REFERENCE: "PROJECT_PUBLIC_LIBRARY_REFERENCE"
    });
    expect(PUBLIC_LIBRARY_AUDIT_FIELDS).toContain("sourceFileSha256");
    expect(PUBLIC_LIBRARY_AUDIT_FIELDS).toContain("publicDocumentVersionId");
  });
});
