-- APM-053 Task 5: audit vocabulary for internal drawing selection commands.
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DRAWING_SELECTION_SET_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DRAWING_SELECTION_ITEM_ADDED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DRAWING_SELECTION_ITEM_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DRAWING_SELECTION_SET_LOCKED';
ALTER TYPE "AuditObjectType" ADD VALUE IF NOT EXISTS 'DRAWING_SELECTION_SET';
ALTER TYPE "AuditObjectType" ADD VALUE IF NOT EXISTS 'DRAWING_SELECTION_ITEM';
